### ISSUE TITLE
[style] Use prettier instead of clang-format

### ISSUE THREAD

**Issue by dayo09** [Samsung/ONE-vscode#1447]
## What?

How about we use prettier for this project instead of clang-format?

## Why?

There are three reasons

(1) To follow the trend. 
[This npm trend graph](https://npmtrends.com/beautify-vs-clang-format-vs-prettier) shows that prettier overwhelms clang-format in npm echo system. 
![1103-npmtrends](https://user-images.githubusercontent.com/17171963/199672687-2926264b-4385-42e0-8574-0745b3374055.png)

(2) To use null-coalescing operator(`??`)
#1445 the operator is not considered correct by clang-format, therefore it breaks it into `? ?`, which makes compilation error.

(3) (personally) It looks better.

It seems that prettier understands typescript better and prettify `objects` or `arrow functions` much better.
 
![1103-prettier](https://user-images.githubusercontent.com/17171963/199672313-15228322-ffc0-4844-8374-e59e745e0e4d.png)

![1103-2](https://user-images.githubusercontent.com/17171963/199672586-2087ec94-ccef-414c-9a0d-a3b6b9fef20a.png)

![1103-3](https://user-images.githubusercontent.com/17171963/199672592-16d9e491-e75d-47ff-8add-7cbbdc6cbccc.png)

**Comment by dayo09** [comment]
If contributors agree, I plan to
(1) turn off clang-format in CI
(2) format using prettier
(3) turn on prettier in CI
To apply the change.

**Comment by seanshpark** [comment]
(1) I'm not sure about the thrend site really reflects `clang-format` for `JS/TS` usage. We're not using `npm` version of `clang-format`

(2) You can use 
```js
// clang-format off
... `??` ...
// clang-format on
```

(3) Looks better for me too, but 'better' may be a personal preference.

Anyway I'm OK to move to new format and also OK to stay with `clang-format`.

**Comment by dayo09** [comment]
@seanshpark 

> 
> (1) I'm not sure about the thrend site really reflects `clang-format` for `JS/TS` usage. We're not using `npm` version of `clang-format`

Sure. But I think that's because typescript users only use prettier by npm. When they need linter or formatter, it's more natural to get tools from npm, not from apt-get system-wise installation.

> (2) You can use 
> ```js
> // clang-format off
> ... `??` ...
> // clang-format on
> ```

I know this but it's more like a commonly used operator, so it's a bit ugly to use it.

> (3) Looks better for me too, but 'better' may be a personal preference.
> 
> Anyway I'm OK to move to new format and also OK to stay with `clang-format`.
> 

Sure, thanks for sharing your opinion :smile:

**Comment by llFreetimell** [comment]
Following comment is just my two cents :)
Basically, I am okay with both `clang-format` and `prettier`.

---

#### Trends
- I think [npm trend graph](https://npmtrends.com/beautify-vs-clang-format-vs-prettier) is not that good for tracking the trends because `npm` is not a main concern for `clang-format`.
- Instead, I searched the download count at VSCode Extension Marketplace.
  - `clang-format` : About 1M downloads according to [`clang-format` related extensions](https://marketplace.visualstudio.com/search?term=clang-format&target=VSCode&category=All%20categories&sortBy=Relevance)
  - `prettier` : About 24M downloads according to [`prettier` extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)
- Given above statistics, `prettier` may be much trendy than `clang-format`.

#### Special grammars for typescript/javascript
- I found more cases that some of grammar is not considered in `clang-format`
  - https://github.com/google/gts/issues/215#issue-364603326
  - https://github.com/google/gts/issues/247#issue-402153046
- Of course, `clang-format on/off` can resolve these issues, but I prefer to minimize the usage of `clang-format on/off`. (Just my preference)

#### Additional references
- I referred https://github.com/googleapis/google-cloud-node/issues/2842 for this issue.
- It is not an answer, but I think there are lots of discussions even with the actual maintainer.

#### Conclusion
- For me, `prettier` seems better but I am not against with using `clang-format`.
- However, I think `eslint` and `stylelint` should be considered just like `clang-format` because
  - `eslint` and `stylelint` have been used for ONE-vscode in `package.json`. (`csslint` is faded out)
  - `eslint` seems bit more popular than `prettier` according to [npm trend graph](https://npmtrends.com/eslint-vs-prettier-vs-stylelint)

**Comment by dayo09** [comment]
@llFreetimell Thanks for your summary :-D 

> Of course, clang-format on/off can resolve these issues, but I prefer to minimize the usage of clang-format on/off. (Just my preference)

I agree with this. For example, I used `??` to make code simple but putting clang-format on/off makes it more ugly.

> ⭐ However, I think eslint and stylelint should be considered just like clang-format because
> eslint and stylelint have been used for ONE-vscode in package.json. (csslint is faded out)
> eslint seems bit more popular than prettier according to [npm trend graph](https://npmtrends.com/eslint-vs-prettier-vs-stylelint)

FYI, eslint is more a linter than a formatter. The usage of those tools are different, eslint only checks the symantic errors, not style. We do not need to consider about eslint here. :-D

**Comment by dayo09** [comment]
Done :-D
