### ISSUE TITLE
Prepare Docker Execution environment

### ISSUE THREAD

**Issue by dayo09** [Samsung/ONE-vscode#343]
Let's prepare docker execution environment for NPU simulator tool.

## Why?

To enable inference tool for performance/memory inspection.

**Comment by dayo09** [comment]
### Design
Discussed design so far is,

- Local Machine --(transfer file/command via ssh/sdb connection, not ssh extension)--> Remote Machine (Ubuntu/Tizen)
- Run docker on ubuntu machine, execute inside the docker <- `by ssh cli command only`
- pull out result(model, benchmark result, log, ...) to local machine with docker

**Comment by hyunsik-yoon** [comment]
@dayo09 
I'd like to try to elaborate the reason we decide to go with ssh cli (rather than SSH extension).

IMHO, we have to consider two cases with toolchain installed in remote machine.
c1) model files are stored in local Windows machine.
c2) model files are stored in remote machine.

Thinking about c1) 
Assuming a user maintains his/her model file in his/her Windows machine and connects target device to the Windows machine.
In such case, if we support SSH-extension, user have to do
1) open a new vscode
2) connect SSH server 
3) but he/she wants to run a compiled code in _local_ PC. (this experience seems weird)
4-1) ONE-vscode transfers the compiled code to remote machine where toolchain is installed. Toolchain sends the result back to ONE-vscode. Here, we have some mechanisms of passing files and receiving result. (which can be done by ssh cli)
4-2) ONE-vscode transfers the compiled code to target device, which is connected to _local_ machine. (This is done by, ssh cli or SDB)

In the above scenario, if we don't use SSH extension, we don't need step 2) and step 3) can be more intuitive.

c2) can be also done with ssh cli.

**Comment by dayo09** [comment]
@hyunsik-yoon

To tell you my opinion, my main points are,

Point 1. keeping ssh/sdb connection is mandatory in any cases (using ssh-extension or not). Your 4. 5. steps can be done within ubuntu device too.

Point 2.

> 1. open a new vscode by pressing green area (image)
> 2. manually connect remote server through SSH (by entering, e.g., IP)

Those steps cannot be disappeared. When we try to connect to remote machine, we will show up ssh connection UI, which we haven't discussed yet but which I expect to be as similar to the vscode-extension's one.

**Comment by dayo09** [comment]
@hyunsik-yoon BTW I got strayed from the main subject of this issue. (sorry for distraction)

May I move this discussion onto another issue?
