### ISSUE TITLE
Provide welcome page to fresh user

### ISSUE THREAD

**Issue by yunjayh** [Samsung/ONE-vscode#932]
Currently, the user who installed our `ONE-vscode` extension cannot get any information.

Since we have a `ONE view container`, it can be a great place to give a welcome message and a brief guide. 

I'm going to refer to [this link](https://code.visualstudio.com/api/references/contribution-points#contributes.viewsWelcome).

**Comment by yunjayh** [comment]
😮 I totally forgot about it. Thank you for your information..!!

**Comment by hyunsik-yoon** [comment]
@yunjayh Note that #348 code was revoked for some reason. So we don't have the code right now in main branch. :-)

**Comment by yunjayh** [comment]
**[The texts are work in progress]** IMHO with this way, user can get what to do after installing our extension, or opening new window without workspace opened.
![image](https://user-images.githubusercontent.com/50489513/177274738-12818230-4501-46c7-aafd-3c41afaebd72.png)

_Originally posted by @yunjayh in https://github.com/Samsung/ONE-vscode/issues/953#issuecomment-1174727869_

**Comment by jyoungyun** [comment]
Can you use this PR, #972 ?

**Comment by yunjayh** [comment]
> I don't understand why we need `Register Installed Toolchain` button. If the system has toolchain, it will search and show it automatically. Is there any reason you defined this?

The contents are mostly copied from #348. I agree with your thought.

Sure for #972 :smile:

**Comment by jyoungyun** [comment]
> The contents are mostly copied from https://github.com/Samsung/ONE-vscode/pull/348. I agree with your thought.

At that time, we though that the function would be necessary because the actual implementation was not implemented. But for now, I don't think it's necessary because it's automatically searched installed toolchain.

I didn't consider the welcome view in OneExplorerView. However, if you comment out the error throw code in OneExplorerView, you can show the ToolchainView working.

**Comment by yunjayh** [comment]
> you can show the ToolchainView working even though workspace is not set.

The codes for showing `ToolchainView` without workspace is merged thanks to @jyoungyun, but because of timing issue, sometimes `ToolchainView` doesn't show anything even if backend is registered and toolchain has been installed. 
The best way to resolve the issue is find way to remove timing issue. For temporal solution, let's give a guide to user to refresh their toolchain view.

**Comment by hyunsik-yoon** [comment]
>  For temporal solution, let's give a guide to user to refresh their toolchain view.

IMHO 
If solving timing issue won't take too long,
solving timing issue is the better way instead of doing temporal work for welcome view.

One suggestion.
How about start drawing(?) Welcome views? Using old screenshot could confuse people.
Welcome view is just a combination of text and buttons (also in text in package.json) so you can draw(?) your initial version in txt format. :-)

**Comment by yunjayh** [comment]
Both introducing welcome page and treating timing issue has been landed (including some comments). Let's close this issue.
